<?php
if(0==date('N')) {
    $start = strtotime('monday'); // today (this monday)
} else {
    $start = strtotime('last monday'); // last monday
}

$start = date('j',$start);
?>

<div class="week-chooser">
    <div class="row-fluid  well well-small">
        <?=$this->placeholder('calendar_sidebar')?>
        <h2>Legend</h2>
        <ul class="legend">
            <li><span class="indicator available">&nbsp;</span> Available</li>
            <li><span class="indicator booked">&nbsp;</span> Booked</li>
            <li><span class="indicator unavailable">&nbsp;</span> Unavailable</li>
            <li><span class="indicator disabled">&nbsp;</span> Invalid</li>
        </ul>
    </div>
    <div class="row-fluid">
        <table class="table table-bordered">
            <thead>
                <th></th>
                <th>Monday <?=$start?></th>
                <th>Tuesday <?=$start+1?></th>
                <th>Wednesday <?=$start+2?></th>
                <th>Thursday <?=$start+3?></th>
                <th>Friday <?=$start+4?></th>
                <th>Saturday <?=$start+5?></th>
                <th>Sunday <?=$start+6?></th>
            </thead>
            <?php
            echo '<tr>';
            echo '<td class="hours-column">';
                echo '<ul>';
                $availability = new \Bookingbat\Engine\Availability;
                $i=0;
                foreach($availability->timeIntervals('00:00','24:00') as $time) {
                    echo sprintf('<li style="top:%spx">', $i*25);
                    echo $this->time($time['start']);
                    echo '</li>';
                    $i++;
                }
                echo '</ul>';
            echo '</td>';
            for($day=$start;$day<$start+7;$day++) {
                ?>
                <td class="week-column-container">

                    <ul class="week-column">
                    <?php
                    foreach($this->availability[$day] as $opening) {

                        $dayString = sprintf('%s-%s-%s', $day, $this->month, $this->year);

                        $seconds_past_midnight_start = strtotime($opening['start']) - strtotime('midnight');
                        $hours_past_midnight_start = $seconds_past_midnight_start/60/60;

                        $seconds_length = strtotime($opening['end']) - strtotime($opening['start']);
                        $hours_length = $seconds_length/60/60;

                        $style = sprintf('top:%dpx;',$hours_past_midnight_start*50);
                        $style .= sprintf('height:%dpx',$hours_length*50);

                        $url = $this->url(array(
                            'day' => date('Y-m-d', strtotime($dayString)),
                            'staff' => $this->staff,
                            'service'=>$this->service
                        ), 'make-booking', true);
                        ?>
                        <li class="available {url:'<?=$url?>'}" style="<?=$style?>">
                            <!--<?=$this->time($opening['start'])?>-<?=$this->time($opening['end'])?>-->
                        </li>
                        <?php
                    }
                    ?>

                    <?php
                    foreach($this->booked[$day] as $booking) {

                        $seconds_past_midnight_start = strtotime($booking['start']) - strtotime('midnight');
                        $hours_past_midnight_start = $seconds_past_midnight_start/60/60;

                        $seconds_length = strtotime($booking['end']) - strtotime($booking['start']);
                        $hours_length = $seconds_length/60/60;

                        $style = sprintf('top:%dpx;',$hours_past_midnight_start*50);
                        $style .= sprintf('height:%dpx',$hours_length*50);
                        ?>
                        <li class="booked" style="<?=$style?>">
                            <!--<?=$this->time($booking['start'])?>-<?=$this->time($booking['end'])?>-->
                        </li>
                    <?php
                    }
                    ?>
                    </ul>
                </td>
                <?php
            }
            echo '</tr>';
            ?>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.week-chooser .available').click(function () {
            window.location.href = $(this).metadata().url;
        });
    });
</script>