<ol class="progressmeter">
    <li class="<?=$this->step==1?'current':''?> <?=$this->step>1?'done':''?>">Pick Service</li>
    <li class="<?=$this->step==2?'current':''?> <?=$this->step>2?'done':''?>">Pick Date</li>
    <li class="<?=$this->step==3?'current':''?> <?=$this->step>3?'done':''?>">Pick Duration</li>
    <li class="<?=$this->step==4?'current':''?> <?=$this->step>4?'done':''?>">Pick Start Time</li>
    <li class="<?=$this->step==5?'current':''?> <?=$this->step>5?'done':''?>">Pick Staff</li>
    <li class="<?=$this->step==6?'current':''?> <?=$this->step>6?'done':''?>">Place your Booking</li>
</ol>