language: php

services:
  - mysql

php:
  - 5.4

before_script:
  - php --server=localhost:8888 --docroot=html &
  - mysql -e 'create database bookingbat_phpunit'
  - mysql bookingbat_phpunit < install.sql
  - php composer.phar install --dev --prefer-source

script:
  - vendor/bin/phpunit && vendor/bin/behat --config=behat.yml.travis