<table border="1" class="calendar">
    <tr>
        <th colspan="7">
            <a href="<?php
            if ($this->month == 1) {
                echo $this->url(array('month' => 12, 'year' => $this->year - 1));
            } else {
                echo $this->url(array('month' => $this->month - 1));
            }
            ?>">&Lt;</a>
            <strong><?=$this->month_name?> <?=$this->year?></strong>
            <a href="<?php
            if ($this->month == 12) {
                echo $this->url(array('month' => 1, 'year' => $this->year + 1));
            } else {
                echo $this->url(array('month' => $this->month + 1));
            }
            ?>">&Gt;</a>
        </th>
    </tr>
    <tr>
        <th width="14%">Sunday</th>
        <th width="14%">Monday</th>
        <th width="14%">Tuesday</th>
        <th width="14%">Wednesday</th>
        <th width="14%">Thursday</th>
        <th width="14%">Friday</th>
        <th width="14%">Saturday</th>
    </tr>
    <tr>
        <?php
        for ($day = 1; $day <= $this->number_of_days_in_month; $day++) {
            $dayString = sprintf('%s-%s-%s', $day, $this->month, date('Y'));

            if (1 == $day) {
                switch (strtolower(date('l', strtotime($dayString)))) {
                    case 'sunday':
                        break;
                    case 'monday':
                        $colspan = 1;
                        break;
                    case 'tuesday':
                        $colspan = 2;
                        break;
                    case 'wednesday':
                        $colspan = 3;
                        break;
                    case 'thursday':
                        $colspan = 4;
                        break;
                    case 'friday':
                        $colspan = 5;
                        break;
                    case 'saturday':
                        $colspan = 6;
                        break;
                }
            }

            if (isset($colspan)) {
                echo sprintf('<td colspan="%s"></td>', $colspan);
                unset($colspan);
            }


            $url = $this->url(array(
                'controller' => $this->controller,
                'action' => 'booking',
                'day' => date('Y-m-d', strtotime($dayString)),
                'trainer' => $this->trainer,
                'therapist' => $this->therapist
            ), null, true);

            ?>
            <td>

                <strong><?=date('d', strtotime($dayString))?></strong>
                <br/>
                <?php
                if (isset($this->availability[$day])) {
                    foreach ($this->availability[$day] as $class) {
                        $dayString = sprintf('%s-%s-%s', $day, $this->month, $this->year);
                        $url = $this->url(array(
                            'action' => 'enroll',
                            'date' => date('Y-m-d', strtotime($dayString)),
                            'id' => $class['id']
                        ));
                        echo '<a href="' . $url . '">' . $class['name'] . ' @' . date('h:i a', strtotime($class['time'])) . '</a>';
                    }
                }
                ?>
            </td>
            <?php
            if (date('l', strtotime($dayString)) == 'Saturday') {
                echo '</tr><tr>';
            }

        }
        ?>
    </tr>
</table>