<?= $this->form ?>
<?php
if (!$this->class) {
    return;
}
?>
Enrollment for <?= $this->escape($this->class) ?> on <?= $this->escape($this->date) ?>

<table class="table table-striped">
    <tr>
        <th>User</th>
    </tr>
    <?php
    foreach ($this->classes as $enrollment) {
        ?>
        <tr>
            <td><?=$this->escape($enrollment['username'])?></td>
        </tr>
    <?php
    }
    ?>
</table>