<?php
$this->placeholder('calendar_sidebar')->captureStart();
$this->staffSelector->setAction('?');
echo $this->staffSelector;
?>
<script type="text/javascript">
    $(document).ready(function () {
        $('#staff').change(function () {
            $(this).closest('form')
                .trigger('submit')

        });
    });
</script>
<?php
$this->placeholder('calendar_sidebar')->captureEnd();