<li><a href="<?=$this->url(array(),'services',true)?>">Book An Appointment</a></li>
<?php
$user = bootstrap::getInstance()->getUser();

if('admin'==$user['type']) {
    ?>
    <li><a href="<?= $this->url(
            array('controller' => 'user', 'action' => 'manage'),
            'default',
            true
        ) ?>">Manage Staff</a></li>
    <li><a href="<?= $this->url(
            array('action' => 'manage'),
            'services',
            true
        ) ?>">Manage Services</a></li>
    <?php
}

if($user['id'] && $user['type'] != 'client') {
    ?>
    <li><a href="<?= $this->url(array(),'appointments',true)?>"><?=$user['type']=='admin'?'':'My'?> Appointments</a></li>
    <?php
}

if('staff'==$user['type']) {
    ?>
    <li><a href="<?= $this->url(array(),'availability',true)?>">My Availability</a></li>
    <?php
}

if('admin'==$user['type']) {
    ?>
    <li><a href="<?= $this->url(
            array('controller' => 'settings', 'action' => 'index'),
            'default',
            true
        ) ?>">Settings</a></li>
    <?php
}