<li><a href="/">Home</a></li>
<li><a href="/calendar">Calendar</a></li>
<?php
$user = bootstrap::getInstance()->getUser();

if('admin'==$user['type']) {
    ?>
    <li><a href="<?= $this->url(
            array('controller' => 'user', 'action' => 'manage'),
            'default',
            true
        ) ?>">Manage Users</a></li>
    <?php
}

if('massage-therapist'==$user['type']) {
    ?>

        <li><a href="<?= $this->url(
                array('controller' => 'user', 'action' => 'register'),
                'default',
                true
            ) ?>">New User</a></li>
    <?php
}

if($user['id'] && $user['type'] != 'client') {
    ?>
    <li><a href="<?= $this->url(
            array('controller' => 'massage', 'action' => 'appointments'),
            'default',
            true
        ) ?>">Appointments</a></li>
    <li><a href="<?= $this->url(
            array('controller' => 'massage', 'action' => 'availability'),
            'default',
            true
        ) ?>"><?=$user['type']=='admin'?'Staff':'My'?> Availability</a></li>
    <?php
}

if('admin'==$user['type']) {
    ?>
    <li><a href="<?= $this->url(
            array('controller' => 'settings', 'action' => 'index'),
            'default',
            true
        ) ?>">Settings</a></li>
    <?php
}