<?php
$view = new \Zend_View;
$view->setScriptPath(__DIR__.'/../');

$helper = new \Zend_View_Helper_PaginationControl();
$helper->setView($view);
echo $helper->paginationControl($this->paginator,
    'Sliding',
    'pagination_control.phtml');
?>
<table class="table table-striped">
    <thead>
        <th></th>
        <th>Date &amp; Time</th>
        <th>Duration</th>
        <?php
        if($this->user_type=='admin') {
            ?><th>Staff</th><?php
        }
        ?>
        <th>Client</th>
    </tr>
    <?php
    foreach ($this->paginator ? $this->paginator : $this->appointments as $appointment) {
        ?>
        <tr>
            <?php
            if ($appointment['canceled']) {
                echo '<td>Canceled</td>';
            } else {
                ?>
                <td>
                    <a class="btn btn-warning" href="<?= $this->url(null,array('action' => 'cancel', 'id' => $appointment['id'])) ?>">Cancel</a>
                </td>
            <?php
            }
            ?>

            <td><?=$this->datetime($appointment['date'], $appointment['time'])?></td>
            <td><?=$this->duration($appointment['duration'])?></td>
            <?php
            if($this->user_type=='admin') {
                ?><td><?=$this->escapeHTML($appointment['staff_first_name'] . ' ' . $appointment['staff_last_name'])?></td><?php
            }
            ?>
            <td>
                <?=$this->escapeHTML($appointment['guest_name'])?>
                <br />
                <?=$this->email($appointment['guest_email'])?><br />
                <?=$this->phone($appointment['guest_phone'])?><br />
            </td>
        </tr>
    <?php
    }
    ?>
</table>
<?php
$view = new \Zend_View;
$view->setScriptPath(__DIR__.'/../');

$helper = new \Zend_View_Helper_PaginationControl();
$helper->setView($view);
echo $helper->paginationControl($this->paginator,
    'Sliding',
    'pagination_control.phtml');