<?php
$appointments = isset($this->paginator) ? $this->paginator : $this->appointments;
if(!count($appointments)) {
    ?>
    <div class="alert">
        <strong>No appointments!</strong> You have booked no appointments
    </div>
    <?php
}

if ($this->paginator) {
    echo $this->paginationControl($this->paginator,
        'Sliding',
        'pagination_control.phtml');
}
?>
<table class="table table-striped">
    <thead>
        <th>Status</th>
        <th>Date &amp; Time</th>
        <th>Duration</th>
        <th>Trainer</th>
    </thead>
    <?php
    foreach ($appointments as $appointment) {

        $booking = new Booking(array(
            'today' => date('Y-m-d'),
            'date' => $appointment['date']
        ));

        switch($this->filter) {
            case 'completed':
                if(!$booking->completed()  || $appointment['canceled']) {
                    // filter out this appointment
                    continue 2;
                }
            break;
            case 'cancelled_lost':
                if(!$appointment['canceled'] || !$appointment['lost_credit']) {
                    // filter out this appointment
                    continue 2;
                }
            break;
            case 'cancelled_not_lost':
                if(!$appointment['canceled'] || $appointment['lost_credit']) {
                    // filter out this appointment
                    continue 2;
                }
            break;
            case 'booked':
                if($appointment['canceled'] || $booking->completed()) {
                    // filter out this appointment
                    continue 2;
                }
            break;
        }

        $class = '';
        if($appointment['canceled']) {
            $class = ' class="warning"';
        }
        if($appointment['lost_credit']) {
            $class = ' class="error"';
        }
        if($booking->completed() && !$appointment['canceled']) {
            $class = ' class="success"';
        }
        ?>
        <tr<?=$class?>>
            <?php

            if ($appointment['canceled']) {
                echo '<td>Canceled</td>';
            } else {

                if ($booking->allowCancelByUser()) {
                    ?>
                    <td>
                        <a class="btn btn-warning cancel" data-toggle="tooltip"
                           title="You may cancel this appointment without penalty"
                           href="<?= $this->url(array(
                               'controller' => 'trainer',
                               'action' => 'cancel',
                               'id' => $appointment['id']
                           )) ?>">Cancel</a>
                    </td>
                <?php
                } elseif ($booking->allowCancelLostByUser()) {
                    ?>
                    <td>
                        <a class="btn btn-danger cancel" data-toggle="tooltip"
                           title="You will loose your credit if you cancel this appointment"
                           href="<?= $this->url(array(
                               'controller' => 'trainer',
                               'action' => 'cancel',
                               'id' => $appointment['id']
                           )) ?>">Cancel</a>
                    </td>
                    <?php
                } elseif($booking->completed()) {
                    echo '<td>Completed</td>';
                } else {
                    echo '<td>unknown</td>';
                }
            }
            ?>

            <td><?=$this->datetime($appointment['date'], $appointment['time'])?></td>
            <td><?=$this->duration($appointment['duration'])?></td>
            <td>
                <?=$this->escape($appointment['first_name'] . ' ' . $appointment['last_name'])?><br />
                <?=$this->email($appointment['email'])?><br />
                <?=$this->phone($appointment['phone'])?>
            </td>
        </tr>
    <?php
    }
    ?>
</table>

<script type="text/javascript">
$('.cancel').tooltip();
</script>