<?php
$appointments = isset($this->paginator) ? $this->paginator : $this->appointments;
if ($this->paginator) {
    echo $this->paginationControl($this->paginator,
        'Sliding',
        'pagination_control.phtml');
}

if(!count($appointments)) {
    ?>
    <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>No appointments!</strong> You have no appointments
    </div>
    <?php
} else {
    ?>
    <table class="table table-striped">
        <thead>
            <th></th>
            <th>Date &amp; Time</th>
            <th>Duration</th>
            <th>Client Name</th>
            <th>Client Email</th>
            <th>Client Phone</th>
        </thead>
        <?php
        foreach ($appointments as $appointment) {
            $class = '';
            if($appointment['canceled']) {
                $class = ' class="error"';
            }
            ?>
            <tr<?=$class?>>
                <?php
                if ($appointment['canceled']) {
                    echo '<td>Canceled</td>';
                } else {
                    ?>
                    <td>
                        <a href="<?= $this->url(array('controller' => 'trainer', 'action' => 'cancel', 'id' => $appointment['id'])) ?>">Cancel</a>
                    </td>
                <?php
                }
                ?>

                <td><?=$this->escape($this->datetime($appointment['date'], $appointment['time']))?></td>
                <td><?=$this->escape($this->duration($appointment['duration']))?></td>
                <td><?=$this->escape($appointment['first_name'] . ' ' . $appointment['last_name'])?></td>
                <td><?=$this->escape($appointment['email'])?></td>
                <td><?=$this->escape($appointment['phone'])?></td>
            </tr>
        <?php
        }
        ?>
    </table>
    <?php
}