<a class="btn" href="<?=$this->url('new-service')?>">New Service</a>

<table class="table table-striped table-bordered">
    <thead>
        <th>Action</th>
        <th>ID</th>
        <th>Service Name</th>
        <th>Durations</th>
    </thead>
    <?php
    foreach($this->services as $service) {
        ?>
        <tr class="record-<?=$this->escapeHTML($service['name'])?>">
            <td>
                <?php
                $url = $this->url('edit-service',array(
                    'action'=>'edit',
                    'id'=>$service['id']
                ));
                ?>
                <a class="btn btn-edit" href="<?=$url?>"><i class="icon-pencil"></i>
            <?php
            $url = $this->url('delete-service',array(
                'action'=>'delete',
                'id'=>$service['id']
            ));
            ?>
            <a class="btn btn-delete" href="<?=$url?>"><i class="icon-minus-sign"></i>
            </td>
            <td><?=$this->escapeHTML($service['id'])?></td>
            <td><?=$this->escapeHTML($service['name'])?></td>
            <td><?=$this->escapeHTML($service['durations'])?></td>
        </tr>
        <?php
    }
    ?>
</table>