<a class="btn" href="<?=$this->url(array('action'=>'new'))?>">New Service</a>

<table class="table table-striped table-bordered">
    <thead>
        <th>Action</th>
        <th>ID</th>
        <th>Service Name</th>
        <th>Durations</th>
    </thead>
    <?php
    foreach($this->services as $service) {
        ?>
        <tr class="record-<?=$this->escape($service['name'])?>">
            <td>
                <?php
                $url = $this->url(array(
                    'action'=>'edit',
                    'id'=>$service['id']
                ));
                ?>
                <a class="btn btn-edit" href="<?=$url?>"><i class="icon-pencil"></i></td>
            </td>
            <td><?=$this->escape($service['id'])?></td>
            <td><?=$this->escape($service['name'])?></td>
            <td><?=$this->escape($service['durations'])?></td>
        </tr>
        <?php
    }
    ?>
</table>