<h1>Edit User</h1>
<form action="?" method="post">
    <div class="row-fluid">
        <div class="span3"></div>
        <div class="span3">
            <?= $this->form->username ?>
            <?= $this->form->first_name ?>
            <?= $this->form->last_name ?>
            <?= $this->form->email ?>
        </div>
        <div class="span3">
            <?= $this->form->type ?>
            <?= $this->form->phone ?>
            <?= $this->form->assigned_trainer_userid ?>
            <?= $this->form->condo_id ?>
            <?= $this->form->submit ?>
        </div>
        <div class="span3"></div>
    </div>
</form>