<a class="btn" href="<?= $this->url(
    array('controller' => 'user', 'action' => 'register'),
    null,
    true
) ?>">New User</a>
<?php
echo $this->paginationControl($this->paginator,
    'Sliding',
    'pagination_control.phtml');
?>
<table class="table table-striped">
    <thead>
        <th></th>
        <th>Id</th>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>User Type</th>
    </thead>
    <?php
    foreach ($this->paginator as $user) {
        $edit_url = $this->url(array(
            'controller' => 'user',
            'action' => 'edit',
            'id' => $user['id']),
        null, true);
        ?>
        <tr>
            <td>
                <a class="btn" href="<?=$edit_url?>"><i class="icon-pencil"></i></i></a>
                <a class="btn" href="<?=$this->url(array('staff'=>$user['id']),'availability',true)?>">Availability</a>
            </td>
            <td><?=$this->escape($user['id'])?></td>
            <td><?=$this->escape($user['username'])?></td>
            <td><?=$this->escape($user['first_name'])?></td>
            <td><?=$this->escape($user['last_name'])?></td>
            <td><?=$this->escape($user['email'])?></td>
            <td><div class="badge"><?=$this->escape($user['type'])?></div></td>

        </tr>
    <?php
    }
    ?>
</table>
<?php
echo $this->paginationControl($this->paginator,
    'Sliding',
    'pagination_control.phtml');
?>