<a class="btn" href="<?= $this->url(
    array('controller' => 'user', 'action' => 'register'),
    null,
    true
) ?>">New User</a>
<?php
echo $this->paginationControl($this->paginator,
    'Sliding',
    'pagination_control.phtml');
?>
<table class="table table-striped">
    <thead>
        <th></th>
        <th>Id</th>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>User Type</th>
        <th>Assigned Personal Trainer</th>
        <th>Assigned Condo</th>
    </thead>
    <?php
    foreach ($this->paginator as $user) {
        $edit_url = $this->url(array(
            'controller' => 'user',
            'action' => 'edit',
            'id' => $user['id']),
        null, true);
        ?>
        <tr>
            <td>
                <a class="btn" href="<?=$edit_url?>"><i class="icon-pencil"></i></i></a>
                <?php
                if ($user['type'] == 'client') {
                    ?>
                    <div class="btn-group">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a
                                href="<?= $this->url(array('controller' => 'billing', 'action' => 'servicesused', 'id' => $user['id']), null, true) ?>">
                                    Services Used</a></li>
                            <li><a
                                href="<?= $this->url(array('controller' => 'billing', 'action' => 'paymenthistory', 'id' => $user['id']), null, true) ?>">
                                Payment History</a></li>
                            <li><a
                                href="<?= $this->url(array('controller' => 'billing', 'action' => 'plan', 'id' => $user['id']), null, true) ?>">
                                Billing Plan</a></li><?php
                            if ($user['member']) {
                                ?><li><a
                                    href="<?= $this->url(array('controller' => 'billing', 'action' => 'cancelplan', 'id' => $user['id']), null, true) ?>">
                                    Cancel Plan</a></li><?php
                            }
                            ?>
                        </ul>
                    </div>
                    <?php
                }
                ?>
            </td>
            <td><?=$this->escape($user['id'])?></td>
            <td><?=$this->escape($user['username'])?></td>
            <td><?=$this->escape($user['first_name'])?></td>
            <td><?=$this->escape($user['last_name'])?></td>
            <td><?=$this->escape($user['email'])?></td>
            <td><div class="badge"><?=$this->escape($user['type'])?></div></td>
            <td><?=$this->escape($user['trainer'])?></td>
            <td><?=$this->escape($user['condo'])?></td>

        </tr>
    <?php
    }
    ?>
</table>
<?php
echo $this->paginationControl($this->paginator,
    'Sliding',
    'pagination_control.phtml');
?>