<?php echo $this->doctype(); ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Booking Bat'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <link rel="stylesheet" href="/css/bootstrap.css">

    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/bootstrap-responsive.css">
    <link rel="stylesheet" href="/font-awesome/css/font-awesome.css">

    <?=$this->headLink()?>

    <script src="/jquery-1.7.1.min.js"></script>
    <script src="/jquery.metadata.pack.js"></script>

</head>

<body>

<?=$this->partial('layout/navigation.phtml')?>

<div class="container-fluid">
    <div class="row-fluid">
        <?=$this->partial('layout/messages.phtml')?>
        <?php echo $this->progress; ?>
    </div>
    <div class="row-fluid">
        <div class="span8">
            <?php echo $this->content; ?>
        </div>
        <div class="span4 well well-small">
            <h2>Appointment Summary</h2>
            <?php echo $this->appointment_summary; ?>
        </div>
    </div>

</div>

<footer>
    &copy; 2013 BookingBat
</footer>

<script src="/js/bootstrap.js"></script>
</body>
</html>