<?php
use \Zend\Mvc\Controller\Plugin\FlashMessenger;
$flashMessenger = new FlashMessenger();

if ($flashMessenger->hasMessages()) {
    ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php foreach ($flashMessenger->getMessages() as $msg): ?>
            <?php echo $msg ?>
        <?php endforeach; ?>
    </div>
<?php
}