<li><a href="<?=$this->url('services')?>">Book An Appointment</a></li>
<?php
$user = bootstrap::getInstance()->getUser();

if('admin'==$user['type']) {
    ?>
    <li><a id="btn-manage-staff" href="<?= $this->url('manage-staff')?>">Manage Staff</a></li>
    <li><a href="<?= $this->url('services',array('action' => 'manage'))?>">Manage Services</a></li>
    <?php
}

if($user['id'] && $user['type'] != 'client') {
    ?>
    <li><a href="<?= $this->url('appointments')?>"><?=$user['type']=='admin'?'':'My'?> Appointments</a></li>
    <?php
}

if('staff'==$user['type']) {
    ?>
    <li><a href="<?= $this->url('availability')?>">My Availability</a></li>
    <?php
}