<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="brand" href="/">Booking Bat</a>
            <div class="nav-collapse collapse">
                <ul class="nav nav-pills">
                    <?=$this->partial('layout/navigation-links.phtml')?>
                </ul>
                <p class="pull-right">
                    <?=$this->partial('layout/user-controls.phtml')?>
                </p>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>