<h1>Services We Offer</h1>
<div class="service-menu">

    <div class="pull-right">
        <a class="btn" href="<?=$this->url(array(
            'controller'=>'payment',
            'action'=>'training'
        ),'default',true)?>">Buy Credits</a>
        <a class="btn btn-primary" href="<?= $this->url(array(), 'trainer-calendar',true)?>"><i class="icon-calendar"></i> View Schedule</a>
    </div>

    <strong>Personal Training</strong>
    <p>30 &amp; 60 minute sessions</p>
    <?= $this->partial('billing/training_credits.phtml', array(
        'user' => $this->user,
        'trainer_appointments_total_duration' => $this->trainer_appointments_total_duration
    )) ?>
</div>

<div class="service-menu">
    <div class="pull-right">
        <a class="btn" href="<?=$this->url(array(
            'controller'=>'payment',
            'action'=>'massage'
        ),'default',true)?>">Buy Credits</a>
        <a class="btn btn-primary" href="<?=$this->url(array(), 'calendar', true)?>"><i class="icon-calendar"></i> View Schedule</a>
    </div>

    <strong>Massage Therapy</strong>
    <p>60 &amp; 90 minute sessions</p>
    <?= $this->partial('billing/massage_credits.phtml', array(
        'user' => $this->user,
        'massage_appointments_total_duration' => $this->massage_appointments_total_duration
    )) ?>

</div>

<div class="service-menu">
    <div class="pull-right">
        <a class="btn" href="#">Buy Credits</a>
        <a class="btn btn-primary" href="<?= $this->url(
            array('controller' => 'class', 'action' => 'index'),
            null,
            true
        ) ?>"><i class="icon-bullseye"></i> View Schedule</a>
    </div>

    <strong>Classes</strong>
    <p>30 &amp; 60 minute classes</p>

</div>

<div class="service-menu">
    <div class="pull-right">
        <a class="btn btn-primary" href="<?= $this->url(
            array(
                'controller' => 'trainer',
                'action' => 'index',
                'consultation'=>true
            ),
            null,
            true
        ) ?>"><i class="icon-bullseye"></i> View Schedule</a>
    </div>

    <strong>Fitness Consultation</strong>
    <p>30 minute consultation</p>

</div>