<ul class="nav nav-tabs" id="myTab2">
    <li class="active"><a href="#massage_credits">Credits</a></li>
    <li><a href="#massage_booked">Booked</a></li>
    <li><a href="#massage_cancelled">Cancelled (Not Lost)</a></li>
    <li><a href="#massage_lost">Lost</a></li>
    <li><a href="#massage_completed">Completed</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="massage_credits">
        <?= $this->partial('billing/massage_credits.phtml', array(
            'user' => $this->user,
            'massage_appointments_total_duration' => $this->massage_appointments_total_duration
        )) ?>
    </div>
    <div class="tab-pane" id="massage_booked">
        <?= $this->partial('massage/appointments-client.phtml', array('appointments' => $this->massage_appointments)) ?>
    </div>
</div>


<script>
    $('#myTab2 a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    })
</script>