<div class="row-fluid">
    <div class="span12">
        <h1>Payment History</h1>
        <table class="table table-striped">
            <thead>
                <th>Payment ID</th>
                <th>Serivce</th>
                <th>Quantity</th>
                <th>Amount Paid</th>
                <th>Date &amp; Time</th>
            </thead>
            <?php
            foreach ($this->payments as $payment) {
                ?>
                <tr>
                    <td><?=$this->escape($payment['payment_id'])?></td>
                    <td><div class="label"><?=$this->escape($payment['service'])?></div></td>
                    <td><?=$this->duration($payment['service_quantity'])?></td>
                    <td><?=$this->money($payment['amount_paid'])?></td>
                    <td><?=$this->escape($this->datetime($payment['datetime']))?></td>
                </tr>
            <?php
            }
            ?>
        </table>
    </div>
    <div class="span6">

    </div>
</div>