<div class="row-fluid">
    <div class="span6">
        <?=$this->partial('billing/plan-add.phtml', array(
            'form'=>$this->form
        ))?>
    </div>
    <div class="span6">
        <h1>Current Plan</h1>
        <?php
        if(!count($this->current_plan)) {
            ?>
            <div class="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>No plan!</strong> You have no active plan
            </div>
        <?php
        } else {
            ?>
            <table class="table table-striped">
                <thead>
                <th>Plan</th>
                <th>Start</th>
                <th>End</th>
                </thead>

                <tr class="active-plan">
                    <td><?=$this->escape($this->user->planName($this->current_plan['plan']))?></td>
                    <td><?=$this->escape($this->current_plan['start'])?></td>
                    <td>Active Plan</td>
                </tr>

            </table>
        <?php
        }
        ?>

        <h1>Past Plans</h1>
        <?php
        if(!count($this->past_plans)) {
            ?>
            <div class="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>No past plan!</strong> You have no past plans
            </div>
            <?php
        } else {
            ?>
            <table class="table table-striped">
                <thead>
                <th>Plan</th>
                <th>Start</th>
                <th>End</th>
                </thead>
                <?php
                foreach ($this->past_plans as $plan) {
                    ?>
                    <tr>
                        <td><?=$this->escape($this->user->planName($plan['plan']))?></td>
                        <td><?=$this->escape($plan['start'])?></td>
                        <td><?=$this->escape($plan['end'] ? $plan['end'] : 'Active Plan')?></td>
                    </tr>
                <?php
                }
                ?>
            </table>
            <?php
        }
        ?>


    </div>
</div>