<?php
if ($this->form->isErrors()) {
    foreach ($this->form->getErrorMessages() as $errormessage) {
        echo '<span class="error">' . $this->escape($errormessage) . '</span>';
    }
}
?>
<form action="?" method="post" class="well">
    <h1>Add New Plan</h1>
    <div class="row-fluid">
        <?php
        // these fields aren't shown for admins
        if($this->form->cardNumber) {
            ?>
            <div class="span6">
                <?php
                echo $this->form->cardNumber;
                echo $this->form->expirationDate;
                echo $this->form->firstName;
                echo $this->form->lastName;
                echo $this->form->address;
                ?>
            </div>
            <?php
        }
        ?>
        <div class="span6">
            <?php
            echo $this->form->city;
            echo $this->form->state;
            echo $this->form->zip;
            echo $this->form->email;
            echo $this->form->plan;
            echo $this->form->add;
            ?>
        </div>
    </div>
</form>