<h1>Classes</h1>

<strong>Fame Fitness offers a wide variety of classes. All of our class instructors are certified and specialize in the class they offer.</strong>

<h2>Zumba</h2>
A fun and effective dance class, that uses interval training combing fast and slow rhythms for an effective aerobic workout while at the same time targeting your legs, abs, glutes, and arms. You'll forget you're working out with the sexy but simple moves to dance music like Cha Cha, Salsa, reggaeton, rumba and more. Best of all, you don't need any previous dance experience!

<h2>Boot camp</h2>
Your cardiovascular and muscular fitness will be challenged with this circuit style class incorporating calisthenics, free weights, plyometrics, and an assortment of equipment for a variety of exercises in each session.

<h2>Pilates</h2>
Looking for beautiful posture and sculpted abdominals? This class will deliver results! Improve muscle control, flexibility, and coordination. Experience exercises designated to maximize core strength, while sculpting the muscles of the trunk and hips.

<h2>Yoga</h2>
Classical yoga focuses on learning each pose in order to obtain the maximum benefits and avoid injury. This pure form of traditional yoga will challenge you to adopt correct alignment and positioning during standing poses, forward bends, minor back bends, and basic inversions.

<h2>Cardio Kickboxing</h2>
Achieve endurance, strength, stability, balance, & mental toughness in this kickboxing cardio class. A series of fast paced jabs, punches, shuffles & high kicks are all incorporated into this exhilarating class.

<h2>Aqua Aerobics</h2>
This High-energy, low-impact class is safe to create a big splash! Cardio intervals, water resistance, and specialized equipment will assist you in strengthening and sculpting all major muscle groups. These classes are designed to provide a vigorous full-body workout for all ages and fitness levels.