<?php $this->headLink()->appendStylesheet('css/exercise.css'); ?>

<h1>Maximum Attainable Heart Rate (MAHR) </h1>

<div class="your-mhr well">
    Your MAHR = 182 bpm
</div>

<h2 class="mhr-formula">Maximum Attainable Heart Rate (MAHR) = 200 - Age</h2>

<div class="mhr">
    <strong class="bpm">182 bpm</strong>
    <div class="box">
        <strong>The Red Line Zone 90% to 100% of MAHR : BURN CARBS</strong>
        <p>Training in this zone will only be possible for short periods of time. It effectively trains your fast twitch muscle fibers and helps to develop speed. This zone is reserved for interval running and only the very fit are able to train effectively within this zone.</p>
    </div>

    <strong class="bpm">182 bpm</strong>
    <div class="box">
        <strong>The Red Line Zone 90% to 100% of MAHR : BURN CARBS</strong>
        <p>Training in this zone will only be possible for short periods of time. It effectively trains your fast twitch muscle fibers and helps to develop speed. This zone is reserved for interval running and only the very fit are able to train effectively within this zone.</p>
    </div>

    <strong class="bpm">182 bpm</strong>
    <div class="box">
        <strong>The Red Line Zone 90% to 100% of MAHR : BURN CARBS</strong>
        <p>Training in this zone will only be possible for short periods of time. It effectively trains your fast twitch muscle fibers and helps to develop speed. This zone is reserved for interval running and only the very fit are able to train effectively within this zone.</p>
    </div>

    <strong class="bpm">182 bpm</strong>
    <div class="box">
        <strong>The Red Line Zone 90% to 100% of MAHR : BURN CARBS</strong>
        <p>Training in this zone will only be possible for short periods of time. It effectively trains your fast twitch muscle fibers and helps to develop speed. This zone is reserved for interval running and only the very fit are able to train effectively within this zone.</p>
    </div>
</div>
<img class="mhr-bottomrocker" src="/img/mhr-bottom.gif" />