<div class="row-fluid">
    <div class="span6">
        <h1>Trainer Appointments</h1>
        <?=$this->partial('trainer/appointments-client.phtml', array(
            'appointments' => $this->trainer_appointments
        ))?>
    </div>
    <div class="span6">
        <h1>Massage Appointments</h1>
        <?=$this->partial('massage/appointments-client.phtml', array(
            'appointments' => $this->massage_appointments
        ))?>
    </div>
</div>

<div class="row-fluid">
    <h1>Class Enrollments</h1>
    <table class="table table-striped">
        <thead>
            <th>Class Name</th>
            <th>Class Time</th>
        </thead>
        <?php
        foreach ($this->class_enrollment as $appointment) {
            ?>
            <tr>
                <td><?=$this->escape($appointment['name'])?></td>
                <td><?=$this->escape($appointment['date'])?></td>
            </tr>
        <?php
        }
        ?>
    </table>
</div>